### ISSUE TITLE
Ignore words (regex pattern)

### ISSUE THREAD

**Issue by AlexanderThaller** [mre/freq#5]
Sometimes not all words should be included in the frequency measurement.

To exclude unwanted words a flag should be introduced that accepts a regex for all words that should be excluded.

The flag could look like the following:

* `-e 'Test|Word|Another'`: Exclude words `Test`, `Word`, `Another` from frequency measurement.

**Comment by mre** [comment]
This is done now. 😊 

```sh
echo "lychee chocolate donut mango" | freq --exclude "chocolate|donut"                                                                    ✘ 130 

0.25 - 1 - mango
0.25 - 1 - lychee
```

```sh
echo "lychee chocolate donut mango" | freq --exclude "chocolate" --exclude "donut"

0.25 - 1 - mango
0.25 - 1 - lychee
```

```sh
echo "lychee chocolate donut mango" | freq -e "chocolate" -e "donut"

0.25 - 1 - mango
0.25 - 1 - lychee
```
