### ISSUE TITLE
Filter stopwords (similar to NLTK's stopwords)

### ISSUE THREAD

**Issue by AlexanderThaller** [mre/freq#8]
Probably can utilize https://github.com/loony-bean/stopwords-rs which contains stopword lists for multiple languages and sources.

**Comment by AlexanderThaller** [comment]
Or better https://crates.io/crates/stop-words as that seems to be maintained more.

**Comment by mre** [comment]
Yup, let's try https://crates.io/crates/stop-words then. Wanna create a PR?

**Comment by mre** [comment]
This was done by @AlexanderThaller in #9. 🥳
